<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260129002316 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE auto_glass (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description VARCHAR(1024) DEFAULT NULL, type VARCHAR(255) NOT NULL, number VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE car_door (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, model VARCHAR(255) NOT NULL, color VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tyres (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, width INT NOT NULL, diameter VARCHAR(10) NOT NULL, seasonality VARCHAR(20) DEFAULT NULL, profile INT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE auto_glass');
        $this->addSql('DROP TABLE car_door');
        $this->addSql('DROP TABLE tyres');
    }
}
